[package]
name = "rsbeacon"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rsbeacon"
path = "src/main.rs"

[lib]
name = "rsbeacon"
path = "src/lib.rs"

[dependencies]
rscaller-proto = { path = "../rscaller-proto" }
tokio = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
libc = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
rcgen = "0.13"

[dev-dependencies]
tokio = { workspace = true }
libc = { workspace = true }
