//! Syscall parameter metadata — used by backends to know which args are
//! pointers, their direction, and their size.
//!
//! This is the canonical source for the forwarded syscall set. The kmod
//! path (`kmod/syscalls.c`, generated by `tools/codegen`) is a separate,
//! unrelated marshaling implementation with its own known gaps (see
//! `openspec/changes/add-beacon-smoltcp-xdp-netstack/design.md` D4/D6
//! history) — this table is authoritative only for the seccomp-unotify
//! path (`seccomp.rs`); there is no requirement to keep them in sync.
//!
//! Size conventions:
//! - `Size::FromArg(i)` — runtime size taken from `args[i]` (capped at `MAX_BUF`)
//! - `Size::FromArgScaled(i, n)` — `args[i] * n` bytes (e.g. an array of
//!   `nfds` fixed-size elements) (capped at `MAX_BUF`)
//! - `Size::FromPtrU32(i)` — the size is not a plain scalar arg but a value
//!   *behind* another pointer arg (e.g. `accept4`'s `addrlen`/`getsockopt`'s
//!   `optlen`, both `socklen_t*`) — read 4 bytes (native-endian `u32`) from
//!   the tracee at the address in `args[i]` and use that as the byte count
//!   (capped at `MAX_BUF`). This is what lets `fill_from_meta` size the
//!   *paired* buffer (`addr`/`optval`) at the caller's real declared
//!   capacity instead of a static over-estimate — sizing it too large would
//!   mean [`crate::seccomp::SeccompController::complete`]'s
//!   `process_vm_writev` could overflow the caller's real, smaller
//!   destination buffer when writing the response back.
//! - `Size::Static(n)` — fixed `n` bytes

use std::collections::HashMap;

/// Maximum bytes we'll copy for a single pointer argument.
pub const MAX_BUF: usize = 4096;

/// Read `len` bytes from `pid`'s virtual address `addr` via
/// `process_vm_readv(2)`. Returns `None` on failure (process exited, bad
/// pointer, ...). Shared by [`resolve_size`] (to dereference `socklen_t*`-
/// style size params) and the seccomp controller's own pointer-argument
/// capture.
pub(crate) fn read_tracee_mem(pid: u32, addr: u64, len: usize) -> Option<Vec<u8>> {
    let mut buf = vec![0u8; len];
    let local = libc::iovec {
        iov_base: buf.as_mut_ptr() as *mut libc::c_void,
        iov_len: len,
    };
    let remote = libc::iovec {
        iov_base: addr as *mut libc::c_void,
        iov_len: len,
    };
    let ret = unsafe {
        libc::process_vm_readv(
            pid as libc::pid_t,
            &local as *const libc::iovec,
            1,
            &remote as *const libc::iovec,
            1,
            0,
        )
    };
    if ret < 0 {
        None
    } else {
        buf.truncate(ret as usize);
        Some(buf)
    }
}

/// Write `data` into `pid`'s virtual address `addr` via
/// `process_vm_writev(2)`. Silently ignores failures (process may have
/// exited) — mirrors [`read_tracee_mem`]'s error handling since callers
/// (resuming a possibly-already-gone tracee) can't act on a write failure
/// anyway.
pub(crate) fn write_tracee_mem(pid: u32, addr: u64, data: &[u8]) {
    let local = libc::iovec {
        iov_base: data.as_ptr() as *mut libc::c_void,
        iov_len: data.len(),
    };
    let remote = libc::iovec {
        iov_base: addr as *mut libc::c_void,
        iov_len: data.len(),
    };
    unsafe {
        libc::process_vm_writev(
            pid as libc::pid_t,
            &local as *const libc::iovec,
            1,
            &remote as *const libc::iovec,
            1,
            0,
        );
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Dir {
    In,
    Out,
    InOut,
}

#[derive(Debug, Clone, Copy)]
pub enum PtrType {
    /// NUL-terminated string; copied with strncpy semantics.
    Str,
    /// Opaque byte buffer.
    Buf,
}

#[derive(Debug, Clone, Copy)]
pub enum Size {
    /// Size is the value of `args[i]` at call time (capped at `MAX_BUF`).
    FromArg(usize),
    /// Size is `args[i] * elem_size` (e.g. `nfds * sizeof(struct pollfd)`),
    /// capped at `MAX_BUF`.
    FromArgScaled(usize, usize),
    /// Size is the `u32` value stored at the tracee address held in
    /// `args[i]` (i.e. `args[i]` is itself a pointer to the real size —
    /// `socklen_t*`), capped at `MAX_BUF`. See the module doc for why this
    /// exists. Requires a tracee memory read, so unlike the other variants
    /// this can only be resolved with a `pid` (see [`resolve_size`]).
    FromPtrU32(usize),
    /// Fixed number of bytes.
    Static(usize),
}

/// Metadata for one pointer-type parameter.
#[derive(Debug, Clone)]
pub struct PtrParam {
    /// Argument index (0-5).
    pub idx: u8,
    pub dir: Dir,
    pub ptr_type: PtrType,
    pub size: Size,
}

/// Metadata for one forwarded syscall.
#[derive(Debug, Clone)]
pub struct SyscallMeta {
    /// Linux x86-64 syscall number.
    pub nr: u64,
    /// Only pointer parameters are listed; scalar args need no special handling.
    pub ptr_params: Vec<PtrParam>,
}

/// Build the metadata table for all forwarded syscalls.
///
/// Returns a `HashMap<nr, SyscallMeta>`.
pub fn build_table() -> HashMap<u64, SyscallMeta> {
    let entries = vec![
        // ── 0: read(fd, buf, count) ─────────────────────────────────────────
        SyscallMeta {
            nr: 0,
            ptr_params: vec![PtrParam {
                idx: 1,
                dir: Dir::Out,
                ptr_type: PtrType::Buf,
                size: Size::FromArg(2),
            }],
        },
        // ── 1: write(fd, buf, count) ────────────────────────────────────────
        SyscallMeta {
            nr: 1,
            ptr_params: vec![PtrParam {
                idx: 1,
                dir: Dir::In,
                ptr_type: PtrType::Buf,
                size: Size::FromArg(2),
            }],
        },
        // ── 2: open(filename, flags, mode) ──────────────────────────────────
        SyscallMeta {
            nr: 2,
            ptr_params: vec![PtrParam {
                idx: 0,
                dir: Dir::In,
                ptr_type: PtrType::Str,
                size: Size::Static(MAX_BUF),
            }],
        },
        // ── 3: close(fd) — no pointers ──────────────────────────────────────
        SyscallMeta { nr: 3, ptr_params: vec![] },
        // ── 4: stat(pathname, statbuf) ──────────────────────────────────────
        SyscallMeta {
            nr: 4,
            ptr_params: vec![
                PtrParam { idx: 0, dir: Dir::In,  ptr_type: PtrType::Str, size: Size::Static(MAX_BUF) },
                PtrParam { idx: 1, dir: Dir::Out, ptr_type: PtrType::Buf, size: Size::Static(144) },
            ],
        },
        // ── 5: fstat(fd, statbuf) ───────────────────────────────────────────
        SyscallMeta {
            nr: 5,
            ptr_params: vec![PtrParam {
                idx: 1,
                dir: Dir::Out,
                ptr_type: PtrType::Buf,
                size: Size::Static(144),
            }],
        },
        // ── 6: lstat(pathname, statbuf) ─────────────────────────────────────
        SyscallMeta {
            nr: 6,
            ptr_params: vec![
                PtrParam { idx: 0, dir: Dir::In,  ptr_type: PtrType::Str, size: Size::Static(MAX_BUF) },
                PtrParam { idx: 1, dir: Dir::Out, ptr_type: PtrType::Buf, size: Size::Static(144) },
            ],
        },
        // ── 62: kill(pid, sig) — no pointers ────────────────────────────────
        SyscallMeta { nr: 62, ptr_params: vec![] },
        // ── 78: getdents(fd, dirp, count) ───────────────────────────────────
        SyscallMeta {
            nr: 78,
            ptr_params: vec![PtrParam {
                idx: 1,
                dir: Dir::Out,
                ptr_type: PtrType::Buf,
                size: Size::FromArg(2),
            }],
        },
        // ── 80: chdir(path) ─────────────────────────────────────────────────
        SyscallMeta {
            nr: 80,
            ptr_params: vec![PtrParam {
                idx: 0,
                dir: Dir::In,
                ptr_type: PtrType::Str,
                size: Size::Static(MAX_BUF),
            }],
        },
        // ── 81: fchdir(fd) — no pointers ────────────────────────────────────
        SyscallMeta { nr: 81, ptr_params: vec![] },
        // ── 72: fcntl(fd, cmd, arg) — no pointers ───────────────────────────
        // `arg` carries a pointer for a handful of commands (F_GETLK/
        // F_SETLK/struct flock*, F_GETOWN_EX/struct f_owner_ex*, ...) that
        // sockets never use in practice; the only commands a beacon-owned
        // fd actually needs (F_GETFL/F_SETFL, arg is a plain int) are
        // scalar. See `SmoltcpXdpBackend::sys_fcntl`.
        SyscallMeta { nr: 72, ptr_params: vec![] },
        // ── 16: ioctl(fd, request, argp) ────────────────────────────────────
        // `argp`'s shape depends entirely on `request` — arbitrary for the
        // general syscall, but the one request a beacon-owned socket fd
        // actually needs is `FIONBIO` (verified: this, not `fcntl`, is what
        // CPython's `socket.settimeout()` actually calls on modern Linux —
        // see `SmoltcpXdpBackend::sys_ioctl`), whose `argp` is `int *`: a
        // plain 4-byte scalar. Declared `InOut` rather than `In` so the same
        // shape also covers `FIONREAD` (kernel writes the byte count back)
        // without a second table entry — harmless for `FIONBIO`, which just
        // gets its already-known input value copied back out unused.
        SyscallMeta {
            nr: 16,
            ptr_params: vec![PtrParam { idx: 2, dir: Dir::InOut, ptr_type: PtrType::Buf, size: Size::Static(4) }],
        },
        // ── 217: getdents64(fd, dirp, count) ────────────────────────────────
        SyscallMeta {
            nr: 217,
            ptr_params: vec![PtrParam {
                idx: 1,
                dir: Dir::Out,
                ptr_type: PtrType::Buf,
                size: Size::FromArg(2),
            }],
        },
        // ── 257: openat(dfd, filename, flags, mode) ─────────────────────────
        SyscallMeta {
            nr: 257,
            ptr_params: vec![PtrParam {
                idx: 1,
                dir: Dir::In,
                ptr_type: PtrType::Str,
                size: Size::Static(MAX_BUF),
            }],
        },
        // ── 262: newfstatat(dfd, filename, statbuf, flag) ───────────────────
        SyscallMeta {
            nr: 262,
            ptr_params: vec![
                PtrParam { idx: 1, dir: Dir::In,  ptr_type: PtrType::Str, size: Size::Static(MAX_BUF) },
                PtrParam { idx: 2, dir: Dir::Out, ptr_type: PtrType::Buf, size: Size::Static(144) },
            ],
        },

        // ── Network ──────────────────────────────────────────────────────
        // NOTE: sendmsg(46)/recvmsg(47) are deliberately not covered here —
        // their `struct msghdr` argument carries nested pointers
        // (`msg_iov`, `msg_name`, `msg_control`) that this flat
        // one-level-of-indirection model can't express. See design.md.

        // ── 41: socket(domain, type, protocol) — no pointers ────────────────
        SyscallMeta { nr: 41, ptr_params: vec![] },
        // ── 42: connect(fd, addr, addrlen) ───────────────────────────────────
        // addrlen (arg 2) is a plain scalar here, not a pointer — it *is*
        // the byte count, unlike accept4/getsockopt's `*addrlen`/`*optlen`.
        SyscallMeta {
            nr: 42,
            ptr_params: vec![PtrParam {
                idx: 1,
                dir: Dir::In,
                ptr_type: PtrType::Buf,
                size: Size::FromArg(2),
            }],
        },
        // ── 49: bind(fd, addr, addrlen) — same shape as connect ─────────────
        SyscallMeta {
            nr: 49,
            ptr_params: vec![PtrParam {
                idx: 1,
                dir: Dir::In,
                ptr_type: PtrType::Buf,
                size: Size::FromArg(2),
            }],
        },
        // ── 50: listen(fd, backlog) — no pointers ────────────────────────────
        SyscallMeta { nr: 50, ptr_params: vec![] },
        // ── 44: sendto(fd, buf, len, flags, dest_addr, addrlen) ──────────────
        SyscallMeta {
            nr: 44,
            ptr_params: vec![
                PtrParam { idx: 1, dir: Dir::In, ptr_type: PtrType::Buf, size: Size::FromArg(2) },
                PtrParam { idx: 4, dir: Dir::In, ptr_type: PtrType::Buf, size: Size::FromArg(5) },
            ],
        },
        // ── 45: recvfrom(fd, buf, len, flags, src_addr, addrlen*) ────────────
        // `addrlen` here (arg 5) IS a pointer (`socklen_t*`, INOUT: caller's
        // capacity in, actual sockaddr length out) — unlike sendto's arg 5,
        // which is the plain scalar length of the addr the caller supplied.
        // `src_addr`'s real capacity is only known by dereferencing it, via
        // `Size::FromPtrU32` — see module doc.
        SyscallMeta {
            nr: 45,
            ptr_params: vec![
                PtrParam { idx: 1, dir: Dir::Out, ptr_type: PtrType::Buf, size: Size::FromArg(2) },
                PtrParam { idx: 5, dir: Dir::InOut, ptr_type: PtrType::Buf, size: Size::Static(4) },
                PtrParam { idx: 4, dir: Dir::Out, ptr_type: PtrType::Buf, size: Size::FromPtrU32(5) },
            ],
        },
        // ── 288: accept4(fd, addr, addrlen*, flags) ──────────────────────────
        SyscallMeta {
            nr: 288,
            ptr_params: vec![
                PtrParam { idx: 2, dir: Dir::InOut, ptr_type: PtrType::Buf, size: Size::Static(4) },
                PtrParam { idx: 1, dir: Dir::Out, ptr_type: PtrType::Buf, size: Size::FromPtrU32(2) },
            ],
        },
        // ── 55: getsockopt(fd, level, optname, optval, optlen*) ──────────────
        SyscallMeta {
            nr: 55,
            ptr_params: vec![
                PtrParam { idx: 4, dir: Dir::InOut, ptr_type: PtrType::Buf, size: Size::Static(4) },
                PtrParam { idx: 3, dir: Dir::Out, ptr_type: PtrType::Buf, size: Size::FromPtrU32(4) },
            ],
        },
        // ── 54: setsockopt(fd, level, optname, optval, optlen) ───────────────
        // optlen (arg 4) is a plain scalar IN-only length, unlike
        // getsockopt's `*optlen`.
        SyscallMeta {
            nr: 54,
            ptr_params: vec![PtrParam {
                idx: 3,
                dir: Dir::In,
                ptr_type: PtrType::Buf,
                size: Size::FromArg(4),
            }],
        },
        // ── 7: poll(fds, nfds, timeout) ──────────────────────────────────────
        // `fds` is `struct pollfd[nfds]` (8 bytes/entry: fd:i32, events:i16,
        // revents:i16) — INOUT: `.events` is set by the caller, `.revents`
        // is filled in by the kernel/backend.
        SyscallMeta {
            nr: 7,
            ptr_params: vec![PtrParam {
                idx: 0,
                dir: Dir::InOut,
                ptr_type: PtrType::Buf,
                size: Size::FromArgScaled(1, 8),
            }],
        },
        // ── 271: ppoll(fds, nfds, tmo_ts, sigmask, sigsetsize) ───────────────
        // Raw syscall ABI (unlike the glibc wrapper) takes all 5 args.
        // `tmo_ts`/`sigmask` are captured IN-only for completeness (a
        // backend that honors the timeout/sigmask needs them); neither is
        // ever written back.
        SyscallMeta {
            nr: 271,
            ptr_params: vec![
                PtrParam { idx: 0, dir: Dir::InOut, ptr_type: PtrType::Buf, size: Size::FromArgScaled(1, 8) },
                PtrParam { idx: 2, dir: Dir::In, ptr_type: PtrType::Buf, size: Size::Static(16) },
                PtrParam { idx: 3, dir: Dir::In, ptr_type: PtrType::Buf, size: Size::FromArg(4) },
            ],
        },
    ];

    entries.into_iter().map(|m| (m.nr, m)).collect()
}

/// Return the byte size of a pointer param given the current `args` array
/// and (for [`Size::FromPtrU32`]) a tracee to read the dereferenced size
/// value from. Caps at `MAX_BUF`. Returns `0` if a required tracee read
/// fails (e.g. the size pointer is unreadable) — callers already treat a
/// `0` size as "skip this param" (see `fill_from_meta`).
pub fn resolve_size(param: &PtrParam, args: &[u64; 6], pid: u32) -> usize {
    match param.size {
        Size::FromArg(i) => (args[i] as usize).min(MAX_BUF),
        Size::FromArgScaled(i, elem_size) => {
            (args[i] as usize).saturating_mul(elem_size).min(MAX_BUF)
        }
        Size::FromPtrU32(i) => {
            let ptr = args[i];
            if ptr == 0 {
                return 0;
            }
            match read_tracee_mem(pid, ptr, 4) {
                Some(bytes) if bytes.len() == 4 => {
                    let val = u32::from_ne_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]);
                    (val as usize).min(MAX_BUF)
                }
                _ => 0,
            }
        }
        Size::Static(n) => n,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn from_arg_reads_and_caps_at_max_buf() {
        let param = PtrParam { idx: 1, dir: Dir::In, ptr_type: PtrType::Buf, size: Size::FromArg(2) };
        let mut args = [0u64; 6];
        args[2] = 10;
        assert_eq!(resolve_size(&param, &args, 0), 10);
        args[2] = (MAX_BUF as u64) + 1000;
        assert_eq!(resolve_size(&param, &args, 0), MAX_BUF);
    }

    #[test]
    fn from_arg_scaled_multiplies_and_caps() {
        let param = PtrParam { idx: 0, dir: Dir::InOut, ptr_type: PtrType::Buf, size: Size::FromArgScaled(1, 8) };
        let mut args = [0u64; 6];
        args[1] = 3;
        assert_eq!(resolve_size(&param, &args, 0), 24);
        args[1] = 10_000;
        assert_eq!(resolve_size(&param, &args, 0), MAX_BUF);
    }

    #[test]
    fn from_ptr_u32_with_null_pointer_is_zero() {
        let param = PtrParam { idx: 2, dir: Dir::Out, ptr_type: PtrType::Buf, size: Size::FromPtrU32(2) };
        let args = [0u64; 6];
        assert_eq!(resolve_size(&param, &args, 0), 0);
    }

    #[test]
    fn from_ptr_u32_with_unreadable_pointer_is_zero() {
        // Reading from our own pid at a bogus address should fail cleanly.
        let param = PtrParam { idx: 2, dir: Dir::Out, ptr_type: PtrType::Buf, size: Size::FromPtrU32(2) };
        let mut args = [0u64; 6];
        args[2] = 0x1; // unmapped/invalid address
        let my_pid = std::process::id();
        assert_eq!(resolve_size(&param, &args, my_pid), 0);
    }

    #[test]
    fn from_ptr_u32_reads_real_value_from_self() {
        // Exercise the real process_vm_readv path against our own process,
        // which is allowed (a process can always read its own memory via
        // process_vm_readv, no special privilege needed for same-pid).
        let capacity: u32 = 16;
        let param = PtrParam { idx: 2, dir: Dir::Out, ptr_type: PtrType::Buf, size: Size::FromPtrU32(2) };
        let mut args = [0u64; 6];
        args[2] = &capacity as *const u32 as u64;
        let my_pid = std::process::id();
        assert_eq!(resolve_size(&param, &args, my_pid), 16);
    }

    #[test]
    fn static_size_is_fixed() {
        let param = PtrParam { idx: 1, dir: Dir::In, ptr_type: PtrType::Buf, size: Size::Static(144) };
        let args = [0u64; 6];
        assert_eq!(resolve_size(&param, &args, 0), 144);
    }

    #[test]
    fn build_table_has_entries_for_every_socket_syscall_except_deferred_msg_variants() {
        let table = build_table();
        for nr in [41u64, 42, 44, 45, 49, 50, 54, 55, 288, 7, 271] {
            assert!(table.contains_key(&nr), "missing metadata for syscall nr={nr}");
        }
        // sendmsg/recvmsg are deliberately deferred — see module doc.
        assert!(!table.contains_key(&46));
        assert!(!table.contains_key(&47));
    }

    #[test]
    fn accept4_addrlen_precedes_or_matches_addr_dependency() {
        // Not a strict ordering requirement (resolve_size re-reads
        // independently), but confirms both params exist with the expected
        // directions/sizing relationship.
        let table = build_table();
        let meta = table.get(&288).expect("accept4 metadata");
        let addr = meta.ptr_params.iter().find(|p| p.idx == 1).expect("addr param");
        let addrlen = meta.ptr_params.iter().find(|p| p.idx == 2).expect("addrlen param");
        assert_eq!(addr.dir, Dir::Out);
        assert!(matches!(addr.size, Size::FromPtrU32(2)));
        assert_eq!(addrlen.dir, Dir::InOut);
        assert!(matches!(addrlen.size, Size::Static(4)));
    }
}
