[package]
name = "rsclient"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rsclient"
path = "src/main.rs"

[lib]
name = "rsclient"
path = "src/lib.rs"

[dependencies]
ctls = { path = "../ctls" }
rscaller-proto = { path = "../rscaller-proto" }
tokio = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
libc = { workspace = true }
rustls = { workspace = true }
tracing = { workspace = true }
dirs = "5"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
