#include "rscaller.h"

#include <linux/syscalls.h>
#include <linux/dirent.h>
#include <linux/slab.h>
#include <linux/version.h>

#include <linux/module.h>
#include <linux/sched.h>
#include <linux/mm.h>

#include <linux/fs.h>
#include <linux/fcntl.h>   /* AT_FDCWD, AT_SYMLINK_NOFOLLOW */
#include <linux/nsproxy.h>
#include "misssing_defs.h"
#include <linux/delay.h>
#include <linux/init.h>
#include <linux/kernel.h> /* min */
#include <linux/proc_fs.h>
#include <linux/uaccess.h> /* copy_from_user, copy_to_user */
#include <asm/io.h>        /* virt_to_phys */
#include <linux/slab.h>

#include <khook/engine.h>
#include <linux/kprobes.h>
#include "remote_fs.h"
#include "shadow_fd.h"


#if IS_ENABLED(CONFIG_X86) || IS_ENABLED(CONFIG_X86_64)
unsigned long cr0;
#elif IS_ENABLED(CONFIG_ARM64)
void (*update_mapping_prot)(phys_addr_t phys, unsigned long virt, phys_addr_t size, pgprot_t prot);
unsigned long start_rodata;
unsigned long init_begin;
#define section_size init_begin - start_rodata
#endif


#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,6,0)
#define HAVE_PROC_OPS
#endif

/* vm_flags_set/vm_flags_clear: introduced in 6.3 (vm_flags became const).
 * Provide shim for older kernels. */
#if LINUX_VERSION_CODE < KERNEL_VERSION(6, 3, 0)
#define vm_flags_set(vma, flags)   ((vma)->vm_flags |= (flags))
#define vm_flags_clear(vma, flags) ((vma)->vm_flags &= ~(flags))
#endif

/* Cgroup namespace inode number of the target container (--image mode).
 * Written by rscaller-run after starting the container.
 * 0 = disabled. */
static unsigned long container_cgns_inum = 0;
module_param(container_cgns_inum, ulong, 0644);
MODULE_PARM_DESC(container_cgns_inum, "Cgroup namespace inode of the container to intercept");

/* Host-absolute path prefix of binaries to intercept (--progs-folder mode).
 * e.g. /var/lib/docker/overlay2/HASH/merged  or  /opt/my-progs
 * Empty string = disabled. */
static char remote_progs_folder[512] = "";
module_param_string(remote_progs_folder, remote_progs_folder, sizeof(remote_progs_folder), 0644);
MODULE_PARM_DESC(remote_progs_folder, "Host path prefix of binaries whose syscalls should be forwarded");

/* Set to 1 by rscaller-run via sysfs once Docker exec setup is complete
 * (runc has exited), so the container shell's syscalls get forwarded but
 * runc's own setup syscalls are ignored. */
static unsigned long forwarding_enabled = 0;
module_param(forwarding_enabled, ulong, 0644);
MODULE_PARM_DESC(forwarding_enabled, "1 = forward syscalls from matching container; 0 = disabled");

/* Target name written by rsclient via "TARGET <name>" to /proc/rscaller.
 * Used to identify /rsc/<target>/ prefix paths. */
static char rsc_target_name[RSC_MAX_TARGET] = "";
static DEFINE_SPINLOCK(target_name_lock);

/* Per-slot remote open tracking: if slot was a remote open, remember target. */
static struct { bool active; char target[RSC_MAX_TARGET]; } slot_remote[BUFFER_SIZE];
static DEFINE_SPINLOCK(slot_remote_lock);

static void rsc_slot_set_remote(int slot_idx, const char *target)
{
    unsigned long flags;
    spin_lock_irqsave(&slot_remote_lock, flags);
    slot_remote[slot_idx].active = true;
    strncpy(slot_remote[slot_idx].target, target, RSC_MAX_TARGET - 1);
    slot_remote[slot_idx].target[RSC_MAX_TARGET - 1] = '\0';
    spin_unlock_irqrestore(&slot_remote_lock, flags);
}

static bool rsc_slot_get_remote(int slot_idx, char *out_target)
{
    unsigned long flags;
    bool active;
    spin_lock_irqsave(&slot_remote_lock, flags);
    active = slot_remote[slot_idx].active;
    if (active && out_target)
        strncpy(out_target, slot_remote[slot_idx].target, RSC_MAX_TARGET - 1);
    spin_unlock_irqrestore(&slot_remote_lock, flags);
    return active;
}

static void rsc_slot_clear_remote(int slot_idx)
{
    unsigned long flags;
    spin_lock_irqsave(&slot_remote_lock, flags);
    slot_remote[slot_idx].active = false;
    spin_unlock_irqrestore(&slot_remote_lock, flags);
}

/* Set to 1 during module exit so new submissions are rejected and in-flight
 * threads can drain before khook_cleanup(). */
static atomic_t shutting_down = ATOMIC_INIT(0);

/* Number of threads currently blocked in control_buffer_wait_result(). */
static atomic_t in_flight = ATOMIC_INIT(0);

/* Number of CPUs currently executing anywhere inside the hook body.
 * Waited on in __exit before calling cleanup_hooks() so module memory
 * is not freed while hook code is still running on another CPU. */
static atomic_t hooks_executing = ATOMIC_INIT(0);

/* Set to 1 when rsclient opens /proc/rscaller; 0 when it closes.
 * Intercept only while a client is actively connected to avoid blocking
 * all userspace processes when no relay is running. */
static atomic_t rsclient_active = ATOMIC_INIT(0);

#define DEVICE_NAME "rscaller"

static ssize_t rscaller_proc_read(struct file *, char __user *, size_t, loff_t *);
/* rscaller_patch_ptr_params is generated by tools/codegen into kmod/syscalls.c
 * and declared in handler_wrappers.h (included via rscaller.h). */

#ifdef HAVE_PROC_OPS
static const struct proc_ops rscaller_ops = {
	.proc_open    = rscaller_dev_open_new,
	.proc_read    = rscaller_proc_read,
	.proc_mmap    = rscaller_dev_mmap_new,
	.proc_release = rscaller_dev_release_new,
	.proc_write   = rscaller_proc_write,
};
#else
static const struct file_operations rscaller_ops = {
	.mmap    = rscaller_dev_mmap,
	.release = rscaller_dev_release,
	.write   = rscaller_proc_write,
};
#endif

static const void* rscaller_ops_ptr = (void*)&rscaller_ops;


#if LINUX_VERSION_CODE > KERNEL_VERSION(4, 16, 0)
static inline void write_cr0_forced(unsigned long val)
{
	unsigned long __force_order;

	asm volatile(
		"mov %0, %%cr0"
		: "+r"(val), "+m"(__force_order));
}
#endif

static inline void smap_write_enable(void)
{
#if IS_ENABLED(CONFIG_X86) || IS_ENABLED(CONFIG_X86_64)
#if LINUX_VERSION_CODE > KERNEL_VERSION(4, 16, 0)
	write_cr0_forced(cr0);
#else
	write_cr0(cr0);
#endif
#elif IS_ENABLED(CONFIG_ARM64)
	update_mapping_prot(__pa_symbol(start_rodata), (unsigned long)start_rodata,
			section_size, PAGE_KERNEL_RO);

#endif
}

static inline void smap_write_disable(void)
{
#if IS_ENABLED(CONFIG_X86) || IS_ENABLED(CONFIG_X86_64)
#if LINUX_VERSION_CODE > KERNEL_VERSION(4, 16, 0)
	write_cr0_forced(cr0 & ~0x00010000);
#else
	write_cr0(cr0 & ~0x00010000);
#endif
#elif IS_ENABLED(CONFIG_ARM64)
	update_mapping_prot(__pa_symbol(start_rodata), (unsigned long)start_rodata,
			section_size, PAGE_KERNEL);
#endif
}

static inline void smap_rw_disable(void)
{
	stac();
}

static inline void smap_rw_enable(void)
{
	clac();
}


// TODO: separately handle userspace char buffers
int save_syscall_param(SyscallParam *buf, long param, int param_idx,
                       const SyscallSignature *signature, int slot_idx)
{
	void* inner_buf;
	bool is_ptr = signature->params_meta[param_idx].is_ptr;
	int type_variant = signature->params_meta[param_idx].type;
	size_t param_size = signature->params_meta[param_idx].size;
	size_t sig_size = param_size; /* preserve before fetch_param_variant clobbers it */
	int direction = signature->params_meta[param_idx].direction;

	fetch_param_variant(buf, type_variant, &inner_buf, &param_size);
	/* fetch_param_variant sets param_size = sizeof(C type), which is wrong for
	 * pointer params (e.g. sizeof(char*) = 8 instead of 4096).  Restore. */
	if (is_ptr)
		param_size = sig_size;

	if (is_ptr) {
		ParamBuf *pb = &global_ctl_buffer->bufs[slot_idx].params[param_idx];

		/* patch_ptr_params runs first and sets user_ptr for all known pointer
		 * params. Only populate pb here if it wasn't already handled. */
		if (pb->user_ptr == 0) {
			pb->user_ptr  = (uint64_t)param;
			pb->size      = (uint32_t)param_size;
			pb->direction = (uint32_t)direction;

			if (direction == PARAM_DIR_IN || direction == PARAM_DIR_INOUT) {
				if (copy_from_user(pb->data, (const void __user *)param, param_size)) {
					pr_err("Failed to copy IN param data from user space");
					return -EFAULT;
				}
			} else {
				memset(pb->data, 0, param_size);
			}
		}

		/* Store the raw userspace pointer in the SyscallParam union so the
		 * relay sees it in args[] (the relay replaces it with a local ptr). */
		memcpy(inner_buf, &param, sizeof(unsigned long));
	} else {
		/* Bug F fix: param is a value, not a pointer — use &param */
		memcpy(inner_buf, &param, param_size);
	}

	return 0;
}

/* Bug A fix: add return syscall; before err: label; fix goto to free syscall */
Syscall* save_syscall(unsigned long *params, const SyscallSignature *signature, int slot_idx) {
	Syscall* syscall;
	int ret;
	int i;

	syscall = kvmalloc(sizeof(Syscall), GFP_KERNEL);
	if (syscall == NULL) {
		pr_err("Failed to alloc syscall buf");
		return NULL;
	}
	memset(syscall, 0, sizeof(Syscall));
	syscall->n_params = signature->n_params;

	for (i = 0; i < signature->n_params; i++) {
		RSC_LOG("rscaller: Trying to save param %d", i);
		ret = save_syscall_param(&(syscall->param_bufs[i]), params[i], i, signature, slot_idx);
		if (ret != 0) {
			pr_err("Failed to save syscall params");
			goto err;
		}
	}

	RSC_LOG("rscaller: Saved syscall params");
	return syscall;  /* success */

err:
	kvfree(syscall);
	return NULL;
}


/* Returns true (filter OUT / don't forward) if the current process should not
 * have its syscalls forwarded.  Two independent filter modes:
 *   - cgroup ns inode: all processes in a container share one unique inode
 *   - progs folder:    binary exe path starts with remote_progs_folder prefix
 * If neither is configured, nothing is forwarded. */
bool filter_binary(void) {
	/* --- cgroup namespace mode --- */
	if (container_cgns_inum != 0) {
		struct cgroup_namespace *cgns;
		if (!forwarding_enabled)
			return true;
		if (!current->nsproxy)
			return true;
		cgns = current->nsproxy->cgroup_ns;
		if (!cgns)
			return true;
		return cgns->ns.inum != container_cgns_inum;
	}

	/* --- remote_progs_folder prefix mode --- */
	if (remote_progs_folder[0] != '\0') {
		struct file *exe;
		char *buf, *path;
		bool filter_out = true;
		size_t prefix_len = strlen(remote_progs_folder);
		/* Strip trailing whitespace/newlines written by sysfs tee */
		while (prefix_len > 0 && (remote_progs_folder[prefix_len - 1] == '\n' ||
		                           remote_progs_folder[prefix_len - 1] == '\r' ||
		                           remote_progs_folder[prefix_len - 1] == ' '))
			prefix_len--;

		if (!current->mm)
			return true;

		exe = current->mm->exe_file;
		if (!exe)
			return true;

		buf = kmalloc(PATH_MAX, GFP_KERNEL);
		if (!buf)
			return true;

		path = d_path(&exe->f_path, buf, PATH_MAX);
		if (!IS_ERR(path) && strncmp(path, remote_progs_folder, prefix_len) == 0)
			filter_out = false;

		kfree(buf);
		return filter_out;
	}

	/* nothing configured: intercept all, rely on path pre-filter */
	return false;
}

/* Syscall/param pairs that hold pathname strings */
static bool rsc_param_is_path(int nr, int param_idx)
{
	/* open: arg0=pathname */
	if (nr == 2 && param_idx == 0) return true;
	/* openat: arg1=pathname */
	if (nr == 257 && param_idx == 1) return true;
	/* stat: arg0=pathname */
	if (nr == 4 && param_idx == 0) return true;
	/* lstat: arg0=pathname */
	if (nr == 6 && param_idx == 0) return true;
	/* newfstatat: arg1=pathname */
	if (nr == 262 && param_idx == 1) return true;
	/* chdir: arg0=pathname */
	if (nr == 80 && param_idx == 0) return true;
	return false;
}

/* Returns true if any path param was resolved to a remote path.
 * Fills out_target with the target name (from the first remote path found). */
static bool rsc_fixup_paths(int slot_idx, int nr, char *out_target)
{
	int i;
	bool found_remote = false;

	for (i = 0; i < MAX_PARAMS; i++) {
		ParamBuf *pb = &global_ctl_buffer->bufs[slot_idx].params[i];
		char target[RSC_MAX_TARGET];
		char resolved[512];

		if (!rsc_param_is_path(nr, i))
			continue;
		if (pb->size == 0 || pb->user_ptr == 0)
			continue;

		pb->data[pb->size < MAX_PARAM_BUF ? pb->size : MAX_PARAM_BUF - 1] = '\0';

		if (rsc_resolve_kpath((char *)pb->data, target, resolved, sizeof(resolved))) {
			size_t rlen = strlen(resolved) + 1;
			if (rlen > MAX_PARAM_BUF) rlen = MAX_PARAM_BUF;
			memcpy(pb->data, resolved, rlen);
			pb->size = (uint32_t)(rlen - 1);
			if (!found_remote) {
				strncpy(out_target, target, RSC_MAX_TARGET - 1);
				out_target[RSC_MAX_TARGET - 1] = '\0';
				found_remote = true;
			}
		} else if ((char)pb->data[0] != '/' &&
			   rsc_resolve_relative((char *)pb->data, target, resolved, sizeof(resolved))) {
			size_t rlen = strlen(resolved) + 1;
			if (rlen > MAX_PARAM_BUF) rlen = MAX_PARAM_BUF;
			memcpy(pb->data, resolved, rlen);
			pb->size = (uint32_t)(rlen - 1);
			if (!found_remote) {
				strncpy(out_target, target, RSC_MAX_TARGET - 1);
				out_target[RSC_MAX_TARGET - 1] = '\0';
				found_remote = true;
			}
		} else if (strncmp((char *)pb->data, "/proc/", 6) == 0) {
			/* /proc remapping: forward absolute /proc/ paths to remote when CWD is remote.
			 * Whitelist /proc/self, /proc/<current-pid>/, /proc/sys/ — those must stay local. */
			char pid_prefix[32];
			char cwd_target[RSC_MAX_TARGET];
			snprintf(pid_prefix, sizeof(pid_prefix), "/proc/%d/", (int)current->pid);
			if (strncmp((char *)pb->data, "/proc/self", 10) != 0 &&
			    strncmp((char *)pb->data, pid_prefix, strlen(pid_prefix)) != 0 &&
			    strncmp((char *)pb->data, "/proc/sys/", 10) != 0 &&
			    rsc_cwd_get(current->pid, cwd_target, NULL)) {
				/* Keep path as-is: rsbeacon opens /proc/xxx on the remote machine */
				if (!found_remote) {
					strncpy(out_target, cwd_target, RSC_MAX_TARGET - 1);
					out_target[RSC_MAX_TARGET - 1] = '\0';
					found_remote = true;
				}
			}
		}
	}
	return found_remote;
}

inline int handle_syscall_common(const struct pt_regs *pt_regs,
                                  SyscallSignature *signature,
                                  int *ret) {
	Syscall *syscall;
	int slot_idx;
	int i;
	unsigned long params[6] = {
		pt_regs->di,
		pt_regs->si,
		pt_regs->dx,
		pt_regs->r10,
		pt_regs->r8,
		pt_regs->r9,
	};

	smap_rw_disable();

	if (!atomic_read(&rsclient_active) || atomic_read(&shutting_down)) {
		if (pt_regs->orig_ax == 257)
			printk_ratelimited(KERN_INFO "rscaller: openat filtered: rsclient_active=%d shutting_down=%d\n",
			       atomic_read(&rsclient_active), atomic_read(&shutting_down));
		smap_rw_enable();
		return -1;
	}

	/* Let exit/exit_group terminate the local process normally — no forwarding */
	if (pt_regs->orig_ax == 60 || pt_regs->orig_ax == 231) {
		smap_rw_enable();
		return -1;
	}

	/* Don't forward read/write on stdin/stdout/stderr — those are TTY I/O
	 * and must reach the real fd, not rsbeacon's fd table. */
	if ((pt_regs->orig_ax == 0 || pt_regs->orig_ax == 1) && pt_regs->di < 3) {
		smap_rw_enable();
		return -1;
	}

	if (filter_binary()) {
		if (pt_regs->orig_ax == 257)
			printk_ratelimited(KERN_INFO "rscaller: openat filtered: filter_binary() returned true (comm=%s cgns=%lu target=%lu fwd_enabled=%d)\n",
			       current->comm,
			       (current->nsproxy && current->nsproxy->cgroup_ns) ?
			               current->nsproxy->cgroup_ns->ns.inum : 0UL,
			       container_cgns_inum,
			       (int)forwarding_enabled);
		smap_rw_enable();
		return -1;
	}

	RSC_LOG("rscaller: forwarding syscall %llu (comm=%s)\n",
	       pt_regs->orig_ax, current->comm);

	/* Reserve a slot first so save_syscall can populate that slot's bufs. */
	syscall = kvmalloc(sizeof(Syscall), GFP_KERNEL);
	if (!syscall) {
		smap_rw_enable();
		return -1;
	}
	memset(syscall, 0, sizeof(Syscall));
	syscall->number = (int)pt_regs->orig_ax;
	slot_idx = control_buffer_submit_syscall(global_ctl_buffer, syscall);
	kvfree(syscall);
	if (slot_idx < 0) {
		smap_rw_enable();
		return -1;
	}

	/* Clear stale ParamBuf data from the previous syscall that used this slot. */
	memset(&global_ctl_buffer->bufs[slot_idx], 0, sizeof(SlotBufs));

	/* Now save the params (including IN buffers) into the reserved slot. */
	rscaller_patch_ptr_params((int)pt_regs->orig_ax, params, slot_idx);
	syscall = save_syscall((unsigned long*)&params, signature, slot_idx);
	if (syscall) {
		/* Overwrite the placeholder we submitted earlier with the real syscall. */
		syscall->number = (int)pt_regs->orig_ax;
		memcpy(&global_ctl_buffer->kernel_to_user.nodes[slot_idx], syscall, sizeof(Syscall));
		kvfree(syscall);
	}

	/* Remote path resolution: scan path-type params, resolve /rsc/<target>/ prefixes */
	{
		char resolved_target[RSC_MAX_TARGET] = "";
		bool is_remote = rsc_fixup_paths(slot_idx, (int)pt_regs->orig_ax, resolved_target);

		/* chdir with remote path: don't forward, just update CWD */
		if (is_remote && pt_regs->orig_ax == 80) {
			ParamBuf *pb = &global_ctl_buffer->bufs[slot_idx].params[0];
			pb->data[pb->size < MAX_PARAM_BUF ? pb->size : MAX_PARAM_BUF - 1] = '\0';
			rsc_cwd_set(current->pid, resolved_target, (char *)pb->data);
			pr_info("rscaller: remote chdir %s:%s\n", resolved_target, (char *)pb->data);
			/* Mark slot as cancelled (-1) so rsclient drains and discards it */
			global_ctl_buffer->kernel_to_user.nodes[slot_idx].n_params = -1;
			*ret = 0;
			smap_rw_enable();
			return 0;
		}

		/* For open/openat: remember we need to wrap the remote fd */
		if (is_remote && (pt_regs->orig_ax == 2 || pt_regs->orig_ax == 257)) {
			rsc_slot_set_remote(slot_idx, resolved_target);
		}
	}

	atomic_inc(&in_flight);
	*ret = (int)control_buffer_wait_result(global_ctl_buffer, slot_idx);
	atomic_dec(&in_flight);

	/* If this was a remote open, wrap the remote fd in an anon_inode */
	{
		char open_target[RSC_MAX_TARGET];
		if ((pt_regs->orig_ax == 2 || pt_regs->orig_ax == 257) &&
		    rsc_slot_get_remote(slot_idx, open_target) &&
		    *ret >= 0) {
			int remote_fd = *ret;
			int local_fd = rsc_shadow_fd_create(remote_fd, open_target);
			if (local_fd >= 0) {
				pr_info("rscaller: remote open -> remote_fd=%d local_anon_fd=%d target=%s\n",
					remote_fd, local_fd, open_target);
				*ret = local_fd;
			}
			rsc_slot_clear_remote(slot_idx);
		}
	}

	/* Skip OUT copy if we were aborted (rsclient disconnect, rmmod, or signal). */
	if (*ret == -ECONNRESET || *ret == -EINTR) {
		smap_rw_enable();
		return -1;
	}

	/* Copy OUT/INOUT param buffers back to userspace.
	 * Check both signature IS_PTR entries AND runtime-patched ParamBufs
	 * (patch_ptr_params sets user_ptr for params not in the signature). */
	for (i = 0; i < MAX_PARAMS; i++) {
		ParamBuf *pb = &global_ctl_buffer->bufs[slot_idx].params[i];
		if ((pb->direction == PARAM_DIR_OUT || pb->direction == PARAM_DIR_INOUT) &&
		    pb->size > 0 && pb->user_ptr) {
			copy_to_user((void __user *)pb->user_ptr, pb->data, pb->size);
		}
	}

	smap_rw_enable();
	return 0;
}

/*
 * Old hand-written patch_ptr_params() was replaced by the auto-generated
 * rscaller_patch_ptr_params() in kmod/syscalls.c (produced by tools/codegen
 * from the tracefs format files + hardcoded fallback metadata).
 */

/* Generic signature: forward all 6 args as opaque longs, no pointer chasing */
static SyscallSignature generic_signature = {
	.n_params = 6,
	.params_meta = {
		{ LONG_TYPE, sizeof(long), NOT_PTR, PARAM_DIR_IN },
		{ LONG_TYPE, sizeof(long), NOT_PTR, PARAM_DIR_IN },
		{ LONG_TYPE, sizeof(long), NOT_PTR, PARAM_DIR_IN },
		{ LONG_TYPE, sizeof(long), NOT_PTR, PARAM_DIR_IN },
		{ LONG_TYPE, sizeof(long), NOT_PTR, PARAM_DIR_IN },
		{ LONG_TYPE, sizeof(long), NOT_PTR, PARAM_DIR_IN },
	},
};

KHOOK_NOREF_EXT(long, x64_sys_call, const struct pt_regs *, unsigned int);
static long khook_x64_sys_call(const struct pt_regs *regs, unsigned int nr)
{
	int ret = 0;
	const SyscallSignature *sig;

	/* Increment at entry; decrement as soon as we leave module code.
	 * KHOOK_ORIGIN runs kernel code (not module code) and can block
	 * arbitrarily long — don't hold hooks_executing across it. */
	atomic_inc(&hooks_executing);

	if (atomic_read(&shutting_down) ||
	    nr == 56 || nr == 57 || nr == 58 || nr == 59 ||
	    nr == 322 || nr == 435) {
		atomic_dec(&hooks_executing);
		return KHOOK_ORIGIN(x64_sys_call, regs, nr);
	}

	/* Remote FS: only intercept for matching processes */
	if (!atomic_read(&rsclient_active) || atomic_read(&shutting_down) || filter_binary()) {
		atomic_dec(&hooks_executing);
		return KHOOK_ORIGIN(x64_sys_call, regs, nr);
	}

	/* --- fd-using syscalls: only forward if fd is a shadow fd --- */
	if (nr == 0 || nr == 1 || nr == 5 || nr == 81 || nr == 217) {
		int fd = (int)regs->di;
		int rfd = rsc_shadow_fd_lookup(fd);
		if (rfd >= 0) {
			struct pt_regs fake = *regs;
			fake.di = (unsigned long)(unsigned int)rfd;
			sig = rscaller_find_signature(nr);
			if (sig && handle_syscall_common(&fake, sig, &ret) == 0) {
				atomic_dec(&hooks_executing);
				return ret;
			}
		}
		/* Not a shadow fd: let kernel handle locally */
		atomic_dec(&hooks_executing);
		return KHOOK_ORIGIN(x64_sys_call, regs, nr);
	}

	/* close(3): forward close(remote_fd) if shadow fd, then close anon_inode */
	if (nr == 3) {
		int fd = (int)regs->di;
		int rfd = rsc_shadow_fd_lookup(fd);
		if (rfd >= 0) {
			struct pt_regs fake = *regs;
			fake.di = (unsigned long)(unsigned int)rfd;
			sig = rscaller_find_signature(nr);
			if (sig) handle_syscall_common(&fake, sig, &ret);
		}
		atomic_dec(&hooks_executing);
		return KHOOK_ORIGIN(x64_sys_call, regs, nr);
	}

	/* --- path-based syscalls: only forward if path resolves to /rsc/ or has remote CWD --- */
	if (nr == 2 || nr == 4 || nr == 6 || nr == 80 ||
	    nr == 257 || nr == 262) {
		const char __user *upath;
		char kpath[512];
		char target[RSC_MAX_TARGET];
		char resolved[512];
		bool is_remote = false;

		/* arg0 holds path for: open(2), stat(4), lstat(6), chdir(80) */
		/* arg1 holds path for: openat(257), newfstatat(262) */
		if (nr == 2 || nr == 4 || nr == 6 || nr == 80)
			upath = (const char __user *)regs->di;
		else
			upath = (const char __user *)regs->si;

		if (upath && strncpy_from_user(kpath, upath, sizeof(kpath)) >= 0) {
			kpath[sizeof(kpath) - 1] = '\0';
			if (rsc_resolve_kpath(kpath, target, resolved, sizeof(resolved))) {
				is_remote = true;
			} else if (kpath[0] != '/' && rsc_cwd_get(current->pid, NULL, NULL)) {
				is_remote = true;
			} else if (strncmp(kpath, "/proc/", 6) == 0) {
				/* /proc remapping: forward if remote CWD set and path not whitelisted */
				char pid_prefix[32];
				snprintf(pid_prefix, sizeof(pid_prefix), "/proc/%d/", (int)current->pid);
				if (strncmp(kpath, "/proc/self", 10) != 0 &&
				    strncmp(kpath, pid_prefix, strlen(pid_prefix)) != 0 &&
				    strncmp(kpath, "/proc/sys/", 10) != 0 &&
				    rsc_cwd_get(current->pid, NULL, NULL))
					is_remote = true;
			}
		}

		if (!is_remote) {
			atomic_dec(&hooks_executing);
			return KHOOK_ORIGIN(x64_sys_call, regs, nr);
		}

		/* Remap stat(4)/lstat(6) → newfstatat(262).
		 * stat/lstat use __old_kernel_stat which is broken on modern 64-bit kernels.
		 * newfstatat with AT_FDCWD is equivalent and always works.
		 * stat(path@di, buf@si)  → newfstatat(AT_FDCWD@di, path@si, buf@dx, flags@r10)
		 */
		if (nr == 4 || nr == 6) {
			struct pt_regs fake = *regs;
			fake.orig_ax = 262;
			fake.di  = (unsigned long)(long)AT_FDCWD;
			fake.si  = regs->di;   /* path */
			fake.dx  = regs->si;   /* buf */
			fake.r10 = (nr == 6) ? AT_SYMLINK_NOFOLLOW : 0;
			sig = rscaller_find_signature(262);
			if (sig && handle_syscall_common(&fake, sig, &ret) == 0) {
				atomic_dec(&hooks_executing);
				return ret;
			}
			atomic_dec(&hooks_executing);
			return KHOOK_ORIGIN(x64_sys_call, regs, nr);
		}

		sig = rscaller_find_signature(nr);
		if (!sig) {
			atomic_dec(&hooks_executing);
			return KHOOK_ORIGIN(x64_sys_call, regs, nr);
		}
		if (handle_syscall_common(regs, sig, &ret) == 0) {
			atomic_dec(&hooks_executing);
			return ret;
		}
		atomic_dec(&hooks_executing);
		return KHOOK_ORIGIN(x64_sys_call, regs, nr);
	}

	/* --- kill/tkill/tgkill: forward only if process has remote CWD --- */
	if (nr == 62 || nr == 200 || nr == 234) {
		char cwd_target[RSC_MAX_TARGET];
		if (rsc_cwd_get(current->pid, cwd_target, NULL)) {
			sig = rscaller_find_signature(nr);
			if (sig && handle_syscall_common(regs, sig, &ret) == 0) {
				atomic_dec(&hooks_executing);
				return ret;
			}
		}
		atomic_dec(&hooks_executing);
		return KHOOK_ORIGIN(x64_sys_call, regs, nr);
	}

	/* All other syscalls: local only */
	atomic_dec(&hooks_executing);
	return KHOOK_ORIGIN(x64_sys_call, regs, nr);
}

int init_hooks(void) {
	return khook_init(NULL);
}

void cleanup_hooks(void) {
	khook_cleanup();
}


static int rscaller_dev_open_new(struct inode *inodep, struct file *filep) {
	int ret = 0;

	if (!mutex_trylock(&ctl_buffer_mutex)) {
		RSC_LOG("rscaller: device busy!\n");
		ret = -EBUSY;
		goto out;
	}

	RSC_LOG("rscaller: device opened\n");
	atomic_set(&rsclient_active, 1);

out:
	return ret;
}


static int rscaller_dev_mmap_old(struct inode *inodp, struct file *filp) {
	RSC_LOG("rscaller_dev_mmap_old");
	return 0;
}

static int rscaller_dev_mmap_new(struct file *filp, struct vm_area_struct *vma)
{
	unsigned long size = vma->vm_end - vma->vm_start;
	int ret;

	pr_info("rscaller: mmap size=%lu PAGE_ALIGN(CB)=%lu CB=%lu\n",
		size, PAGE_ALIGN(sizeof(ControlBuffer)), sizeof(ControlBuffer));

	/* mmap() rounds len up to PAGE_SIZE; allow that */
	if (size > PAGE_ALIGN(sizeof(ControlBuffer))) {
		pr_info("rscaller: mmap EINVAL size check\n");
		return -EINVAL;
	}

	vm_flags_set(vma, VM_IO | VM_DONTEXPAND | VM_DONTDUMP);

	/* remap_pfn_range works correctly for multi-page __get_free_pages
	 * allocations; vm_insert_page fails on tail pages (compound page
	 * tail pages have refcount 0). */
	ret = remap_pfn_range(vma, vma->vm_start,
	                      virt_to_phys(global_ctl_buffer) >> PAGE_SHIFT,
	                      size, vma->vm_page_prot);
	return ret;
}

/* Bug B fix: private_data is never set, remove free_page/kfree — only unlock */
static int rscaller_dev_release_new(struct inode *inode, struct file *filp)
{
	int i;
	RSC_LOG("rscaller: release\n");
	atomic_set(&rsclient_active, 0);
	/* Wake up any processes blocked in control_buffer_wait_result so they
	 * don't stay in D state forever after rsclient disconnects. */
	for (i = 0; i < BUFFER_SIZE; i++)
		control_buffer_complete(global_ctl_buffer, i, -ECONNRESET);
	mutex_unlock(&ctl_buffer_mutex);
	return 0;
}

/* Stub proc_read to allow O_RDWR opens (kernel rejects read flag without this) */
static ssize_t rscaller_proc_read(struct file *file, char __user *buf,
                                   size_t count, loff_t *ppos)
{
	return 0;
}

/* Format: "DONE <slot_idx> <retval>\n" or "TARGET <name>\n" */
ssize_t rscaller_proc_write(struct file *file, const char __user *buf,
                             size_t count, loff_t *ppos) {
	char kbuf[64];
	pr_info("rscaller: proc_write count=%zu\n", count);
	int slot_idx;
	long retval;
	char tname[RSC_MAX_TARGET];

	if (count >= sizeof(kbuf))
		return -EINVAL;
	if (copy_from_user(kbuf, buf, count))
		return -EFAULT;
	kbuf[count] = '\0';

	if (sscanf(kbuf, "DONE %d %ld", &slot_idx, &retval) == 2) {
		if (slot_idx >= 0 && slot_idx < BUFFER_SIZE) {
			control_buffer_complete(global_ctl_buffer, slot_idx, retval);
		}
	} else if (sscanf(kbuf, "TARGET %63s", tname) == 1) {
		unsigned long flags;
		spin_lock_irqsave(&target_name_lock, flags);
		strncpy(rsc_target_name, tname, RSC_MAX_TARGET - 1);
		rsc_target_name[RSC_MAX_TARGET - 1] = '\0';
		spin_unlock_irqrestore(&target_name_lock, flags);
		pr_info("rscaller: target set to '%s'\n", rsc_target_name);
	}
	return count;
}

/* Bug D fix: ret initialized to 0 */
static int __init rscaller_init(void)
{
	int ret = 0;

	RSC_LOG("Rscaller init");

	rsc_remote_fs_init();
	memset(slot_remote, 0, sizeof(slot_remote));

	global_ctl_buffer = control_buffer_new();

	if ((ret = init_hooks())) {
		pr_err("Failed to register hooks");
		return ret;
	}

	proc_create(DEVICE_NAME, 0666, NULL, rscaller_ops_ptr);

	return 0;
}

static void __exit rscaller_cleanup(void)
{
	int i;

	/* Signal shutdown: reject new submissions, wake all blocked waiters. */
	atomic_set(&shutting_down, 1);
	atomic_set(&rsclient_active, 0);
	for (i = 0; i < BUFFER_SIZE; i++)
		control_buffer_complete(global_ctl_buffer, i, -ECONNRESET);

	/* Wait for threads in control_buffer_wait_result to drain. */
	while (atomic_read(&in_flight) > 0)
		msleep(10);

	/* Wait for threads currently inside our hook body to exit.
	 * hooks_executing is decremented before KHOOK_ORIGIN, so this
	 * only tracks the brief in-module portion (not blocking syscalls). */
	{
		int waited = 0;
		while (atomic_read(&hooks_executing) > 0 && waited++ < 100)
			msleep(1);
	}

	/* Revert the x64_sys_call patch. No new threads can enter after this. */
	cleanup_hooks();

	/* After cleanup_hooks(), threads that were in KHOOK_ORIGIN may still
	 * return through a few instructions of our hook code. Give them time
	 * to pass through, then quiesce all CPUs. */
	msleep(50);
	synchronize_rcu();
	remove_proc_entry(DEVICE_NAME, NULL);
	control_buffer_free(global_ctl_buffer);
	rsc_remote_fs_exit();
}

static void vm_close(struct vm_area_struct *vma)
{
	RSC_LOG("vm_close\n");
}


module_init(rscaller_init);
module_exit(rscaller_cleanup);

MODULE_LICENSE("GPL");
MODULE_AUTHOR("your mom");
MODULE_DESCRIPTION("Rscaller kmod");
